language: python

python:
    - "3.7.0"
addons:
  postgresql: "9.6"

env:
    - repo_token: $REPO_TOKEN

install:
    - pip install -r requirements.txt
    - pip install coveralls

before_script:
    - psql -c "create database iot_dashboard;" -U postgres
    - sudo redis-server /etc/redis/redis.conf --port 6379

script:
    - python manage.py test
    - coverage
    - coveralls

after_success:
    - coveralls
